### PR TITLE
Braintree vs select2

### PR DESCRIPTION
**Pull request by torotil**
### Problem

Braintree’s hosted fields seem to have issues with select2 enabled selects.

### Proposed solution

Disable select2 on braintree forms.

### CODE REVIEW

**Review by katzmo — CHANGES_REQUESTED** [review]
Thanks, it’s good to have an on-off switch for select2!

It would be nicer to make pretty selects work with braintree pseudo fields, but if turning select2 off is the only ways, I'm fine with it.

However, please add the payment_form_alter after `campaignion_foundation_form_alter()` to keep some order in the file ;)

Have you checked the same issue does not occur for other payment methods too, e.g. Stripe?

**Comment by torotil** [comment]
> It would be nicer to make pretty selects work with braintree pseudo fields, but if turning select2 off is the only ways, I'm fine with it.

I don’t think this is going to work with the hosted fields (fields displayed in an iframe). Do you see a way how this could work?
 
> However, please add the payment_form_alter after `campaignion_foundation_form_alter()` to keep some order in the file ;)

Ok, I’ve moved the code up. I thought it was better suited down where the `select-two` code resides.

> Have you checked the same issue does not occur for other payment methods too, e.g. Stripe?

Nope. I haven’t had enough time to look left and right as this was not even scheduled work.

**Comment by katzmo** [comment]
> I don’t think this is going to work with the hosted fields (fields displayed in an iframe). Do you see a way how this could work?

No, I don’t think there is one. But this means we'll have the same issue for all payment methods using hosted fields.

**Review by katzmo — APPROVED** [review]

**Comment by torotil** [comment]
> But this means we'll have the same issue for all payment methods using hosted fields.

The issue doesn’t occur with stripe.

**Comment by katzmo** [comment]
> The issue doesn’t occur with stripe.
 
Interesting. Because Stripe doesn’t (try to) use a select field?

**Comment by torotil** [comment]
> > The issue doesn’t occur with stripe.
> 
> Interesting. Because Stripe doesn’t (try to) use a select field?

… or Stripe maybe didn’t c&p their JS from braintree so it doesn’t work in exactly the same way.

**Comment by katzmo** [comment]
I'd still be hard to initialize any js on a select field in an iFrame, no matter what code is used :wink: 

But the Stripe expire date is a single text field.

**Comment by torotil** [comment]
> I'd still be hard to initialize any js on a select field in an iFrame, no matter what code is used

It’s the braintree JS that throws an error when select2 was initialized first - not the other way round. Something with an infinite recursion in a data attribute of the select.

[Sorry accidentally edited your comment instead of answering.]

**Pull request merged**
